### ISSUE TITLE
!random with numbers doesn't work

### ISSUE THREAD

**Issue by zuzak** [zuzakistan/civilservant#396]
You should be able to do `!random 5` but the bot doesn't output anything if you try.

I think this is because the function in question outputs a Number: https://github.com/zuzakistan/civilservant/blob/master/modules/random.js#L8

whereas the output formatter doesn't support it:  https://github.com/zuzakistan/civilservant/blob/master/modules/_commands.js#L6-L21

To fix this bug, either:
* change the output formatter to correctly handle numbers (harder), or
* coerce the output of the random command's function to be a string (easier)

**Comment by zuzak** [comment]
Looks like this doesn't work.
We've accidentally applied the fix to the wrong part of the `!random` command: the part that picks a random choice from a list (`!random foo bar baz`) as opposed to a random number (`!random 5`).

We're converting a string to a string, which wasn't broken.
The problem is with the second `return` statement; the first one was fine.

Sorry about this; I should've caught this during code review.

**Comment by G-Thompson-Ops** [comment]
I need help understanding the logic here @zuzak - Is this statement saying in real terms if the message is two words long (!random 12) : `else if (msg.args.length === 2)` then do some maths then return an int (which is this case is res)?

In this case we just need to rester res.toString in order to solve this issue - although I still don't fully understand the else logic, nor how the math actually works (Where in the below statement it uses the number we specified?) 
`var res = Math.floor(Math.random() * Math.floor(msg.args[1]))`
